name: Documentation
description: Writing, diagrams, GitHub Pages, or reproducibility work
title: "[DOC] "
labels: ["documentation"]
assignees:
  - DuranKaanAltin

body:
  
  - type: dropdown
    id: target_milestone
    attributes:
      label: Target Milestone
      description: Select which milestone this issue belongs to (auto-assigned by workflow).
      options:
        - M1 - Setup & Baseline Lock
        - M2 - Transport-Limited Analysis
        - M3 - Electrical Response Integration
        - M4 - Sensitivity & Design Insights
        - M5 - Finalization & Submission
    validations:
      required: true
  
  - type: textarea
    id: scope
    attributes:
      label: Documentation Scope
      description: What will be documented?
      placeholder: Reproducibility steps for COMSOL model
    validations:
      required: true

  - type: textarea
    id: audience
    attributes:
      label: Target Audience
      description: Who is this documentation for?
      placeholder: CMPE coordinators, academic reviewers
    validations:
      required: true

  - type: textarea
    id: output
    attributes:
      label: Expected Output
      description: File or page to be produced.
      placeholder: docs/reproducibility.md
    validations:
      required: true

  - type: textarea
    id: done
    attributes:
      label: Definition of Done
      description: Completion criteria.
      placeholder: Page renders correctly on GitHub Pages
    validations:
      required: true